### ISSUE TITLE
Some css changes to make 'log-simpread' and 'logseq-dev-theme' work together

### ISSUE THREAD

**Issue by mmmmtttt** [OverflowCat/logseq-simpread#6]
First, thank the author @OverflowCat for developing this useful plugin. 
I use 'paper theme', and found similar display problem as described in #5.
With the following changes in css file, it works. (However, i'm not expert on CSS, so this is just an ad hoc try😆)

```css
/*add these two rules*/
body{
  height: 100vh;
}

#root{
  position: fixed;
  width: 100%;
}

.sidebar-item-list {
  /* comment out following three lines*/
  /* padding-top: var(--ct-header-height);
  position: absolute;
  top: 0; */
  width: 100%;
  padding-left: 1rem;
  padding-right: 1rem;
}

.scrollbar-spacing {
  /* and comment out this line*/
  /* height: 100%; */
  overflow: auto !important;
  scrollbar-gutter: stable;
}



```

**Comment by OverflowCat** [comment]
Many thanks! This rule is the key:

```css
.sidebar-item-list {
  position: absolute;
}
```

A new version has been available in marketplace, and works here.

![image](https://user-images.githubusercontent.com/20166026/211193636-4ad4df28-a809-47b6-a351-0eaed2dc5dfb.png)

Note that you may need to click the button twice the first time you use after launch if the tab does not switch successfully.

Other rules are the same as default or just adjusting the appearance, and I didn't see the difference. Please tell me if I miss something.
